### ISSUE TITLE
Doesn't work with recent Postfix versions

### ISSUE THREAD

**Issue by brian-maloney** [kumina/postfix_exporter#1]
While this seems to work with the Postfix version included with CentOS 6 (Postfix 2.6), with more recent versions such as Postfix 3.1 it does not work.  In Postfix 2.6, /var/spool/postfix/public/showq spits out mailq-formatted output, but in Postfix 3.1 it's a machine-readable format that looks like this:

queue_nameholdqueue_id9A070A4time1489455573size1018sendertest@domain.comrecipienttest@domain.comreason

I am going to try to develop a patch that can consume both formats, but if someone else beats me to it that's fine too.

**Comment by brian-maloney** [comment]
Looks like there are ASCII NULL's between each of those strings, btw.

**Comment by EdSchouten** [comment]
Thanks for reporting this. At Kumina, we don't have any Postfix 3.1 systems yet, so that's why we haven't run into this yet.

Are records still separated by newlines? If so, it should be possible to reuse the existing scanner loop to process the input. It could fall back to parsing this format in case the existing regular expression pattern doesn't match.

**Comment by brian-maloney** [comment]
Unfortunately it looks like the "lines" are separated by 3 null bytes and then the output is terminated by 4 null bytes.  That's what I get from empirically looking at it.  I think a look at the Postfix source is in order to confirm this framing.

**Comment by EdSchouten** [comment]
Ah, okay. That's unfortunate. Question: could you please attach a copy of the raw data to this ticket? I can take a look if you want.

**Comment by brian-maloney** [comment]
Here's an example with 3 messages in the queue:

root@concord:~# socat UNIX-CLIENT:/var/spool/postfix/public/showq STDIO
queue_nameholdqueue_idCB3E8B4time1489707918size438sendertest@domain.comrecipienttest@domain.comreasonqueue_nameholdqueue_id0A329A4time1489707918size438sendertest@domain.comrecipienttest@domain.comreasonqueue_nameholdqueue_id0F10B96time1489707917size438sendertest@domain.comrecipienttest@domain.comreason

root@concord:socat -x UNIX-CLIENT:/var/spool/postfix/public/showq OPEN:/dev/null                                                                   
         > 2017/03/16 23:49:05.080958  length=116 from=0 to=115
71 75 65 75 65 5f 6e 61 6d 65 00 68 6f 6c 64 00 71 75 65 75 65 5f 69 64 00 43 42 33 45 38 42 34 00 74 69 6d 65 00 31 34 38 39 37 30 37 39 31 38 00 73 69 7a 65 00 34 33 38 00 73 65 6e 64 65 72 00 74 65 73 74 40 64 6f 6d 61 69 6e 2e 63 6f 6d 00 72 65 63 69 70 69 65 6e 74 00 74 65 73 74 40 64 6f 6d 61 69 6e 2e 63 6f 6d 00 72 65 61 73 6f 6e 00 00 00                                                                                                      
          > 2017/03/16 23:49:05.081129  length=233 from=116 to=348                                                                                               
71 75 65 75 65 5f 6e 61 6d 65 00 68 6f 6c 64 00 71 75 65 75 65 5f 69 64 00 30 41 33 32 39 41 34 00 74 69 6d 65 00 31 34 38 39 37 30 37 39 31 38 00 73 69 7a 65 00 34 33 38 00 73 65 6e 64 65 72 00 74 65 73 74 40 64 6f 6d 61 69 6e 2e 63 6f 6d 00 72 65 63 69 70 69 65 6e 74 00 74 65 73 74 40 64 6f 6d 61 69 6e 2e 63 6f 6d 00 72 65 61 73 6f 6e 00 00 00 71 75 65 75 65 5f 6e 61 6d 65 00 68 6f 6c 64 00 71 75 65 75 65 5f 69 64 00 30 46 31 30 42 39 36 00 74 69 6d 65 00 31 34 38 39 37 30 37 39 31 37 00 73 69 7a 65 00 34 33 38 00 73 65 6e 64 65 72 00 74 65 73 74 40 64 6f 6d 61 69 6e 2e 63 6f 6d 00 72 65 63 69 70 69 65 6e 74 00 74 65 73 74 40 64 6f 6d 61 69 6e 2e 63 6f 6d 00 72 65 61 73 6f 6e 00 00 00 00                                                   
root@concord:~#

**Comment by EdSchouten** [comment]
Thanks for providing the example. Could you please give the latest code a try? Thanks!

**Comment by brian-maloney** [comment]
It's working in the general sense.  One thing, the histogram seems to be inverted:

# HELP postfix_queue_message_age_seconds Age of messages in Postfix's message queue, in seconds
# TYPE postfix_queue_message_age_seconds histogram
postfix_queue_message_age_seconds_bucket{le="10"} 0
postfix_queue_message_age_seconds_bucket{le="100"} 0
postfix_queue_message_age_seconds_bucket{le="1000"} 1
postfix_queue_message_age_seconds_bucket{le="10000"} 1
postfix_queue_message_age_seconds_bucket{le="100000"} 1
postfix_queue_message_age_seconds_bucket{le="1e+06"} 1
postfix_queue_message_age_seconds_bucket{le="1e+07"} 1
postfix_queue_message_age_seconds_bucket{le="1e+08"} 1
postfix_queue_message_age_seconds_bucket{le="+Inf"} 1
postfix_queue_message_age_seconds_sum 321.6972498893738
postfix_queue_message_age_seconds_count 1
# HELP postfix_queue_message_size_bytes Size of messages in Postfix's message queue, in bytes
# TYPE postfix_queue_message_size_bytes histogram
postfix_queue_message_size_bytes_bucket{le="1000"} 1
postfix_queue_message_size_bytes_bucket{le="10000"} 1
postfix_queue_message_size_bytes_bucket{le="100000"} 1
postfix_queue_message_size_bytes_bucket{le="1e+06"} 1
postfix_queue_message_size_bytes_bucket{le="1e+07"} 1
postfix_queue_message_size_bytes_bucket{le="1e+08"} 1
postfix_queue_message_size_bytes_bucket{le="1e+09"} 1
postfix_queue_message_size_bytes_bucket{le="+Inf"} 1
postfix_queue_message_size_bytes_sum 460
postfix_queue_message_size_bytes_count 1
# HELP postfix_up Whether scraping Postfix's metrics was successful.
# TYPE postfix_up gauge
postfix_up 1

**Comment by brian-maloney** [comment]
Nevermind the histogram thing, I read up on it and see that le= is the _upper_ bound of the bucket, rather than the lower bound.  I'm closing this now, thanks for the work implementing this!
