### ISSUE TITLE
metrics from systemd-journal are not updated after a while

### ISSUE THREAD

**Issue by WilliButz** [kumina/postfix_exporter#10]
When I set up this exporter it seemed to work fine at first, but after a while I noticed that some metrics did not get updated anymore. In particular all metrics that come from the systemd-journal:

![grafana visualisation](https://user-images.githubusercontent.com/20464732/37612761-66c39d90-2ba6-11e8-96ca-5ffe5ae13d46.png)

There were still new log messages coming in from the postfix unit, so I went looking for an issue with the exporter itself. As there were no error messages coming from the exporter, I started to strace it and then added some debug output, to find out what was going on. 
After a while I found out that this [Next()](https://github.com/kumina/postfix_exporter/blob/1d584386e426f4c31681af78cf200325024f19df/systemd.go#L51) call kept returning `(0, nil)` for each consecutive access to the log after some time.

It's still not clear to me why this happens exactly but I 'fixed' it by adding the following to [postfix_exporter.go](https://github.com/kumina/postfix_exporter/blob/master/postfix_exporter.go#L408-L424):
```diff
@@ -409,6 +409,10 @@ func (e *PostfixExporter) CollectLogfileFromJournal() error {
        e.journal.Lock()
        defer e.journal.Unlock()
 
+       r := e.journal.Wait(time.Duration(1) * time.Second)
+       if r < 0 {
+               log.Print("error while waiting for journal!")
+       }
        for {
                m, c, err := e.journal.NextMessage()
                if err != nil {
```
I found this in a test of the [`go-systemd`](https://github.com/coreos/go-systemd/blob/master/sdjournal/journal_test.go#L493-L496) library that is used here.

I'm not sure wether this is an appropriate solution for this or if anyone else even experiences the same issue :)

Additional info:
* the exporter does not crash, it just keeps serving the (unchanged) metrics
* metrics from the showq socket are not affected by this and are updated continuously
* I'm using the tagged version `0.1.0` on `Linux 4.15` with `systemd 234` and `postfix 3.2.5`
* the exporter does not output any error messages at any time
* as the added Wait() call did fix the issue for me, I assume that it does not have anything to do with postfix itself

**Comment by BartVerc** [comment]
@silkeh are you familiar with this problem? 
Because we do not use the systemd journal feature ourselfs.

**Comment by silkeh** [comment]
Can confirm this is an issue, though in my situation it takes a lot longer for the bug to trigger (up to a week). Solution seems appropriate (or at least not harmful), but I'll take a closer look later in the week.

**Comment by silkeh** [comment]
I'm still not sure why this happens, but the patch *does* seem to fix it.

@WilliButz can you submit a PR with this patch?

**Comment by WilliButz** [comment]
@silkeh sure :)
