### ISSUE TITLE
Make systemd optional

### ISSUE THREAD

**Issue by mrueg** [kumina/postfix_exporter#11]
Is it possible to create a build tag to disable systemd for this exporter?
Not everyone has it installed, and if you build from source the systemd headers are required to build it.

**Comment by BartVerc** [comment]
With the build_static.sh script it is possible to build. Is that an option for you?

**Comment by mrueg** [comment]
@BartVerc It's not an option, as we can't run docker containers during build. I'd like to package it for Gentoo Linux.
