### ISSUE TITLE
Truncating logfiles is really bad...

### ISSUE THREAD

**Issue by theq86** [kumina/postfix_exporter#14]
Instead, processed log entries should at least be written to a separate file which holds all already processed log entries.

A better approach would be to save a pointer somewhere and save the last read position of the logfile. Then fseek to it and go on reading.
If logrotate or something else is in place, you can also save a hash value of the first line in the file. Since logfiles are append only you can reliably determine, if a logfile is all new and never read so you can start reading it from the beginning.

Truncating is the worst since it destroys all log data. Prometheus metrics are no substitution for that.

**Comment by bastischubert** [comment]
We use a separate log file that is read/truncated by the exporter and no one else.
No logrotation necessary, no state files as well.

 You might do it that way too.

**Comment by flyhard** [comment]
As far as I can see, there is no truncating anymore. If that is correct, this issue might be closed

**Comment by flyhard** [comment]
See #24

**Comment by ptman** [comment]
If truncating is no longer happening, should the default just be to read the normal postfix logfile?

**Comment by ptman** [comment]
Oh, another thing: it seems that the flag documentation was overwritten by some later PR: https://github.com/kumina/postfix_exporter/blob/master/main.go#L20

**Comment by flyhard** [comment]
I aggree. I'll put up a PR.
