### ISSUE TITLE
misleading metric names 

### ISSUE THREAD

**Issue by bastischubert** [kumina/postfix_exporter#15]
hi there,

postfix_showq_message_size_bytes_count -> shows the count of messages in the queue and has nothing to do with either size nor bytes

you might want to rename that metric name

**Comment by BartVerc** [comment]
This is an automatic metric of Histograms with prefix `_count`.

**Comment by bastischubert** [comment]
Too bad you are ignoring prometheus best practices/recommendations on metric names. 

I'll try a merge request instead ;)
