### ISSUE TITLE
Support for multiple instances

### ISSUE THREAD

**Issue by ktosiek** [kumina/postfix_exporter#19]
Is there a suggested way of supporting multiple postfix instances on one host?
Currently it seems I'd need a separate postfix_exporter for each postfix instance, and have to add the instance name in Prometheus scrape configuration.

**Comment by BartVerc** [comment]
An option is to configure syslog to write mail log into one logfile as mentioned in the readme, but then you lose the instance information.
Our advise is to have a separate postfix_exporter per instance.

**Comment by timstoop** [comment]
I'd say so as well. If you can run multiple postfix instances on a machine (for which I also don't really understand the use case, tbh), having an exporter for each shouldn't be a problem either.

**Comment by olvsa** [comment]
After some tries using this exporter in _Postfix multiple instances environment_ I wrote own exporter for queue state.
[github.com/olvsa/postqueue_jq](https://github.com/olvsa/postqueue_jq)
