### ISSUE TITLE
use systemd's sd_journal api to get log messages

### ISSUE THREAD

**Issue by ibotty** [kumina/postfix_exporter#2]
That way, one does not have to set up syslogd writing to a new file, it is also more performant (not that that matters much).

The C functions one would use are:
 * `sd_journal_open(3)` or `sd_journal_open_directory(3)` (preferably make it configurable to specify the directory, for postfix running in containers),
 * `sd_journal_add_match(3)` to match for the right unit (will be "postfix.service" most of the time, but could be configurable),
 * `sd_journal_seek_head(3)` (or `sd_journal_seek_cursor(3)` if you want to jump to a previous position),
 * `sd_journal_next(3)` and `sd_journal_get_data(3)` to get the raw data, you are moste likely interested in the "MESSAGE"  only.

**Comment by EdSchouten** [comment]
Sounds like a good idea to me! Just make sure that the file-based processing is retained, as there are lots of systems out there that don't use systemd (older Linux distros, BSD, containers, etc).
