### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by rezizter** [kumina/postfix_exporter#21]
Do you perhaps have a Grafana dash json to import?

**Comment by BartVerc** [comment]
[postfix_grafana.json.txt](https://github.com/kumina/postfix_exporter/files/2675129/postfix_grafana.json.txt)

This is the json template of our dashboard. It is based on our federated setup recordingrules. Therefore, I am not sure if this helps.

**Comment by curantes** [comment]
> [postfix_grafana.json.txt](https://github.com/kumina/postfix_exporter/files/2675129/postfix_grafana.json.txt)
> 
> This is the json template of our dashboard. It is based on our federated setup recordingrules. Therefore, I am not sure if this helps.

@BartVerc could you also share the recording rules you use with this dashboard? 
Thanks!

**Comment by anarcat** [comment]
anyone else started working on this? i started rolling my own before realizing this existed. i wonder how hard it would be to convert @BartVerc's dashboard into something that works without resampling rules...

**Comment by anarcat** [comment]
I made a dashboard based on @BartVerc's work and published it on grafana.com:

https://grafana.com/dashboards/10013

It seems to work okay, although I have no data for the `lmtp` daemon. I also wonder how useful the TLS Cipher section really is: the cardinality of that one is kind of huge and it doesn't say anything really useful. What would be nice is the ratio of protocol use (none, TLS 1.0, 1.1, 1.2, etc) but I couldn't figure out a formula for that. I tried this:

    (sum(rate(postfix_smtpd_tls_connections_total{instance=~"$instance"}[5m])) by (instance)) / (sum(rate(postfix_smtpd_connects_total{instance=~"$instance"}[5m])) by (instance))

But that gave the wrong numbers (e.g. something larger than 1) for some series. I nevertheless included *something* that might be useful.

Is this sufficient to close this ticket? Maybe a PR to add it to the readme?

**Comment by BartVerc** [comment]
@anarcat nice work!

The metric `postfix_lmtp_messages_processed_total` used in the "Message processing rate" graph shows indeed no data. The recording rule expression we use is this: `avg(rate(postfix_lmtp_delivery_delay_seconds_count{job="postfix_exporter"}[15m])) by (instance)`.

About the TLS cipher, we use this recording rule (which I combined from multiple federated setups) :
`avg_over_time( sum by(cipher, protocol, trust) (rate(postfix_smtpd_tls_connections_total{job="postfix_exporter"}[5m]))[1d])`
Same for `smtp`. This never gives us numbers larger than 1.

**Comment by anarcat** [comment]
i see. it seems like i don't have any `postfix_lmtp_delivery_delay_seconds_count` metrics either - presumably we don't have any LTMP transport setup anywhere. it's probably still worth fixing that expression in our dashboard, so I'll do so next. 

this rule fails to "compile" here:

    avg_over_time( sum by(cipher, protocol, trust) (rate(postfix_smtpd_tls_connections_total{job="postfix_exporter"}[5m]))[1d])

... at least in a Prometheus query, which fails with:

> Error executing query: parse error at char 120: range specification must be preceded by a metric selector, but follows a *promql.AggregateExpr instead

This works, but gives much lower results than I was hoping for...

     avg( sum by(cipher, protocol, trust) (rate(postfix_smtpd_tls_connections_total{job="postfix"}[5m])))

btw, I have published the dashboards not only on grafana.com but also this git repo now:

<https://gitlab.com/anarcat/grafana-dashboards>

i hope that's useful...

**Comment by rezizter** [comment]
Dash looks great. Thank you soo much

**Comment by anarcat** [comment]
thanks! should we link it from the README?
