### ISSUE TITLE
Truncating log files is racy

### ISSUE THREAD

**Issue by groner** [kumina/postfix_exporter#24]
The current truncating behavior can result in messages being missed if they are appended between the time postfix_exporter hits EOF and the time it calls truncate.

To avoid the race it's probably necessary to rename the old log file, drain it (coordinate with syslogd, read until it stops changing for some period of time and/or messages start appearing in the new file), and finally remove the old file.

It's probably easier to use an external log rotation system than to have postfix_exporter coordinate with syslogd (which might be impossible if they're in separate containers).

**Comment by flyhard** [comment]
Is this still an issue? I haven't seen any code that truncates at all.

**Comment by groner** [comment]
It looks like the truncating behavior was removed in b13741290679ef7ab5f06104f396a702d7fc3ee8, and released in v0.2.0.
