### ISSUE TITLE
binary release

### ISSUE THREAD

**Issue by TuxCoder** [kumina/postfix_exporter#25]
Hello,
thanks first for your work!

Is it possible to have to have a binary release, for better auto deployment, like ansible.
ref: https://github.com/debops/debops/pull/160

I see that a debian package is on the way, would be nice until that.
ref: https://lists.debian.org/debian-devel/2019/01/msg00298.html

**Comment by VerosK** [comment]
May I help you with the binary release?

**Comment by bhozar** [comment]
@Ivaylo-Korakov Was this only done the once, or will all future released include a static binary? I do not see one for the current release.

**Comment by rjhenry** [comment]
Doesn't look like there is. If it's of any use, I'm sure I could create a workflow to automatically build on new releases?
