### ISSUE TITLE
smtpTLSLine doesn't match

### ISSUE THREAD

**Issue by Valodim** [kumina/postfix_exporter#35]
Hi there! Thanks for your work on this.

I noticed that in my setup, I'm getting no data points for outgoing TLS connections. I think I traced this down:

> postfix/smtp[14659]: Verified TLS connection established to gmail-smtp-in.l.google.com[2a00:1450:4010:c0f::1b]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256

This is a log line from my postfix. If I'm reading the code right, that is expected to be matched by the regex in this line:
https://github.com/kumina/postfix_exporter/blob/master/postfix_exporter.go#L280

However, the log line has extra stuf after the (256/256 bits), and while the regex expects it to end there "$". I guess there should there be an extra \S* there?

I'm on postfix 3.4.5-1

**Comment by Valodim** [comment]
Reopening this, there does seem to be an issue. The exporter counted a total of 2 "verified" (mta-sts) connections over a few days, whereas in my mail.log there are 100+.

This somewhat matches looking over the logs. I have a bunch of lines (100+) like this:
> Jul 24 04:38:17 mail postfix/smtp[30582]: Verified TLS connection established to gmail-smtp-in.l.google.com[108.177.14.26]:25: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256

And could only find one like this:
> Jul 24 03:28:15 mail postfix/smtp[24052]: Verified TLS connection established to mx2.comcast.net[2001:558:fe21:2a::6]:25: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)

So it seems likely to me that the counted verified connection is only the comcast one, which indeed ends with the "(256/256 bits)" pattern, and the gmail one (with more detail) is missed.

**Comment by Ivaylo-Korakov** [comment]
@flyhard thanks for providing a fix and @Valodim for reporting the issue
