### ISSUE TITLE
 undefined: Journal

### ISSUE THREAD

**Issue by frateralexander** [kumina/postfix_exporter#37]
Trying to run exporter I have this error:

go run postfix_exporter.go --postfix.logfile_path=la.log
./postfix_exporter.go:48:13: undefined: Journal

**Comment by Ivaylo-Korakov** [comment]
Hi,

The issue you are having is because when you do `go run` you also need to include the `nosystemd.go` file which has the definition for Journal. 

What you want is:
```sh
go run postfix_exporter.go nosystemd.go --postfix.logfile_path=la.log
```
or
```sh
go run . --postfix.logfile_path=la.log
```

Also, try building the exporter with the provided sh file. Run the following command in the root of the project:
```sh
./build_static.sh
```
