### ISSUE TITLE
List of postfix_smtpd_messages_processed_total growing over time

### ISSUE THREAD

**Issue by m8t** [kumina/postfix_exporter#38]
Hello,

Version: commit https://github.com/kumina/postfix_exporter/commit/af6943b1bc8da0b8c645f4fed63559bba24f114c

The list of sasl can grow by a lot for the metric postfix_smtpd_messages_processed_total (in my case > 35000 entries after about a week). This takes up more memory at exporter side, and an increased number of points scrapped at prometheus side.

I think it could be useful to purge the list regularly. As of right now, a workaround in my case can be handled by the systemd unit file with the option RuntimeMaxSec.

Regards,
Mike

**Comment by m8t** [comment]
Side note, the same issue exists for dovecot_exporter, which keeps in memory all users that have been seen through dovecot stats.

**Comment by Ivaylo-Korakov** [comment]
Hi Mike,

At the moment we are unable to spend time on the postfix exporter.
If you can make a PR with a solution we will definitely take a look.

**Comment by flyhard** [comment]
I see where the issue lies. Usernames have a (possibly) high cardinality, which is not recommended for collecting metrics. 
I would suggest removing this metric or hiding it behind a command-line flag would be a good idea. Both should be relatively easy to do.
