### ISSUE TITLE
 Feature request: Switch to kingpin

### ISSUE THREAD

**Issue by mjtrangoni** [kumina/postfix_exporter#4]
Hi,

Prometheus and many exporters are switching to kingpin. See also prometheus#2455. You will have to do some prometheus vendoring updates, but it should work as a drop-in replacement.

Thanks!

**Comment by timstoop** [comment]
I can see in the issue that the choice is made, but I cannot find where they point out *why* they want to use Kingpin. I must admit I only scanned the issue, as it is quite long, but maybe you could explain here as well? Or copy and paste the main reasons for switching to kingpin? What would it add to the (usability/readability/etc. of the) code that currently isn't there?

**Comment by EdSchouten** [comment]
I just looked into Kingpin. Though it's a pretty nice flags library, I cannot see any advantages to it compared to what we already have.

I do think that uniformity with other Prometheus related projects is good to have, but it's not something that we at Kumina will work on explicitly after releasing such tools initially. Feel free to send a pull request in case you'd like this utility to use Kingpin, as we will merge it for you.
