### ISSUE TITLE
Tailing seems broken

### ISSUE THREAD

**Issue by flyhard** [kumina/postfix_exporter#41]
I am trying to find out why postfix_exporter is underreporting metrics. 

I had postfix_exporter runnning for about a month, and its removed count is not high enough for even a day.

While doing some local debugging I discovered that it seems to read the logfile only when the metrics are requested and at that time it reads only the last couple of lines, not all lines since last time.

I am still trying to create a proper testcase for it, but my test so far is like this:

- I start postfix_exporter on an empty file
- I request the /metrics endpoint
- I append a whole day of logs to the file 
`cat maillog >> tailing_maillog`
- I request the /metrics endpoint again

The last request has the same counter unless one of the last lines is a line to be counted.

**Comment by Ivaylo-Korakov** [comment]
Hi,

Thank you for using the exporter and for noticing the issue.
I have merged your PR. We have plans to improve the exporter and make it work in Kubernetes because we are running into some issues with that but for now, we don't have much time to spend on it. So any help is much appreciated!
