### ISSUE TITLE
Commit 8e63fbbe omits 13 output types for those using systemd.enable & null logfile_path

### ISSUE THREAD

**Issue by trjh** [kumina/postfix_exporter#62]
I installed postfix_exporter compiled from the latest version  [sha 8e63fbbe](https://github.com/kumina/postfix_exporter/commit/8e63fbbe8d67752613c56a5f07390e3521110ed7) and found that data stopped updating in several windows of the [anarcat Postfix dashboard](https://grafana.com/grafana/dashboards/10013).

I compiled a couple of back revisions and ran them manually as follows:
```
sudo -u postfix /usr/local/bin/tmp/postfix_exporter.01.8e63fbb --systemd.enable --postfix.logfile_path=
sudo -u postfix /usr/local/bin/tmp/postfix_exporter.02.bbcbead --systemd.enable --postfix.logfile_path=
```

Comparing the output (with values removed) from `8e63fbb` and `bbcbead`, I found these values missing:
```
% diff -uwb out.01.8e63fbb out.02.bbcbead | grep ^\+\#\ TYPE
+# TYPE postfix_cleanup_messages_not_accepted_total
+# TYPE postfix_cleanup_messages_processed_total
+# TYPE postfix_cleanup_messages_rejected_total
+# TYPE postfix_qmgr_messages_inserted_receipients
+# TYPE postfix_qmgr_messages_inserted_size_bytes
+# TYPE postfix_qmgr_messages_removed_total
+# TYPE postfix_smtp_connection_timed_out_total
+# TYPE postfix_smtp_deferred_messages_total
+# TYPE postfix_smtp_status_deferred
+# TYPE postfix_smtpd_connects_total
+# TYPE postfix_smtpd_disconnects_total
+# TYPE postfix_smtpd_forward_confirmed_reverse_dns_errors_total
+# TYPE postfix_smtpd_sasl_authentication_failures_total
```

I'd suspect a premature return in @k-kinzal 's pull request

**Comment by k-kinzal** [comment]
Oops, I didn't have systemd support.

https://github.com/kumina/postfix_exporter/blob/8e63fbbe8d67752613c56a5f07390e3521110ed7/postfix_exporter.go#L615-L617
https://github.com/kumina/postfix_exporter/blob/8e63fbbe8d67752613c56a5f07390e3521110ed7/postfix_exporter.go#L703-L705
I should have checked both the `e.tailer` and `e.journal` here.
