### ISSUE TITLE
New release(s)

### ISSUE THREAD

**Issue by badgerspoke** [kumina/postfix_exporter#63]
Hi there - this seems like a very useful tool, can I ask if you have plans to make any updated releases - I see that the code is actively maintained but the last release was in early 2019?! 
Thanks in advance

**Comment by anthonyfok** [comment]
Yes, please make a release of the current code as, say, v0.2.1, to facilitate packaging by Linux distributions.
Many thanks in advance!

**Comment by mika** [comment]
Latest commit dates back to 2020-06-03 (~3/4 year ago), @kumina are you still maintaining postfix_exporter?
If so, would be great to see a new release, since quite some commits/fixes happened since then!

Thanks for postfix_exporter! :hugs:

**Comment by bmillemathias** [comment]
Joining the other persons to request a release, they are a fair number of commits and fixes that should have a higher chance to get tested.
Best

**Comment by mika** [comment]
v0.3.0 was released on 2021-10-20 (see https://github.com/kumina/postfix_exporter/releases/tag/0.3.0), thanks for that!

**Comment by ptman** [comment]
@BartVerc close?
