### ISSUE TITLE
Does sometimes not pick up rotated logs

### ISSUE THREAD

**Issue by piotr1212** [kumina/postfix_exporter#78]
According to the readme: `Rotating the log files while the exporter is running is OK.` While this works most of the times, it already happened twice in two days that it does not and the exporter keeps tracking deleted files. 

```

postfix+ 18282     1  0 May11 ?        00:07:50 /usr/local/bin/postfix_exporter --postfix.logfile_path=/var/log/mail.log

ls -l /proc/18282/fd/
total 0
<< skipped >>
lr-x------ 1 postfix-exporter postfix-exporter 64 May 11 11:55 3 -> '/var/log/mail.log.1 (deleted)'

```

rotate config:
```
/var/log/mail.log
{
        rotate 24
        hourly
        missingok
        notifempty
        compress
        delaycompress
        sharedscripts
        maxsize 200M
        postrotate
                /usr/lib/rsyslog/rsyslog-rotate
        endscript
}
```

OS: Ubuntu 18.04 LTS

Running latest commit b050cdff024376d8d2c59b56e0085f3a6ea305f6

BTW could not get journald log working at all, probably related to https://github.com/kumina/postfix_exporter/issues/55

**Comment by piotr1212** [comment]
I see there is a bunch of known issues with hpcloud/tail, switched to a better maintained fork to see if that fixes our issues. Will post update if it works. https://github.com/piotr1212/postfix_exporter/commit/6039f0781e430ec7372202ae4cc8831ddcfbf659

**Comment by piotr1212** [comment]
Been running the version with nxadm/tail on multiple mailservers for 5 days with hourly rotate and the issue did not occur anymore, before this patch it would happen every few hours.

**Comment by travisghansen** [comment]
Even with the updated code I'm still seeing failures. I'm using the busybox syslogd launched as such `syslogd -n -b 0 -s 50000` where the daemon itself does log rotation on it's own (not logrotate). Any ideas what could be causing the sporadic behavior in this setup?

**Comment by piotr1212** [comment]
I also still see it happening once in a while, don't know why. Is much better than before though.

**Comment by travisghansen** [comment]
I toyed with using a named pipe but I didn’t have much luck getting the tail library to properly read data continuously (hacked the code and tried various options in the config struct). Ultimately I resorted to a cronjob to restart the collector on an interval (I run the container with supervisor so restarts are viable).
